import { useState } from "react";
import { Navigate, Route, Routes, useNavigate, useLocation } from "react-router-dom";
import Layout from "./components/Layout";
import { Approvals, Applications, Dashboard, Detail, Evaluation, Knowledge, QA } from "./pages";
import { Button, Input } from "./components/ui";
import { setRole } from "./services/api";
import type { Role } from "./types";
function Login({onLogin}:{onLogin:(r:Role)=>void}){const nav=useNavigate();const [email,setEmail]=useState("alaa@delta.bank");const login=(role:Role)=>{onLogin(role);setRole(role);nav("/")};return <main className="grid min-h-screen place-items-center bg-navy p-5"><div className="absolute h-96 w-96 rounded-full bg-primary/20 blur-[120px]"/><section className="z-10 w-full max-w-md rounded-3xl border border-white/10 bg-card/90 p-8 shadow-glow"><div className="text-center"><img src="/logo.png" alt="DELTA Credit Copilot Logo" className="mx-auto h-16 w-auto"/><h1 className="mt-4 text-2xl font-bold tracking-[.16em]">DELTA</h1><p className="text-sm text-muted">Credit Copilot</p><p className="mt-4 text-sm italic text-muted">Smarter credit decisions. Human approved.</p></div><div className="mt-7 space-y-4"><Input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email address"/><Input type="password" defaultValue="password" placeholder="Password"/><Button className="w-full" onClick={()=>login("loan_officer")}>Login to workspace</Button></div><div className="my-5 border-t border-white/10"/><p className="mb-3 text-center text-xs font-bold text-muted">QUICK DEMO LOGIN</p><div className="grid gap-2 sm:grid-cols-2"><Button className="bg-surface hover:bg-surface/70" onClick={()=>login("loan_officer")}>Loan Officer</Button><Button onClick={()=>login("credit_officer")}>Credit Officer</Button></div></section></main>}
function Workspace(){const [role,setRoleState]=useState<Role>((localStorage.getItem("delta-role") as Role)||"loan_officer");const update=(r:Role)=>{setRoleState(r);localStorage.setItem("delta-role",r)};return <Layout role={role} onRole={update}><Routes><Route path="/" element={<Dashboard/>}/><Route path="/applications" element={<Applications/>}/><Route path="/applications/:id" element={<Detail/>}/><Route path="/qa" element={<QA/>}/><Route path="/knowledge-base" element={<Knowledge/>}/><Route path="/approvals" element={<Approvals role={role}/>}/><Route path="/evaluation" element={<Evaluation/>}/><Route path="*" element={<Navigate to="/" replace/>}/></Routes></Layout>}
export default function App(){const location=useLocation();const login=(r:Role)=>{localStorage.setItem("delta-role",r)};return <Routes><Route path="/login" element={<Login onLogin={login}/>}/><Route path="/*" element={location.pathname==="/login"?<Navigate to="/login"/>:<Workspace/>}/></Routes>}
